// <auto-generated />
using System;
using FinalSay.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalSay.Repository.Migrations
{
    [DbContext(typeof(FinalSayDbContext))]
    partial class FinalSayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalSay.Worker.Contracts.SubmitProposal", b =>
                {
                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProposalId");

                    b.ToTable("Proposal", (string)null);
                });

            modelBuilder.Entity("FinalSay.Worker.Contracts.SubmitProposal", b =>
                {
                    b.OwnsMany("FinalSay.Worker.Contracts.Member", "Members", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("ProposalId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("MemberId");

                            b1.HasIndex("ProposalId");

                            b1.ToTable("Members");

                            b1.WithOwner()
                                .HasForeignKey("ProposalId");
                        });

                    b.OwnsOne("FinalSay.Worker.Contracts.ProposalContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("SubmitProposalProposalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SubmitProposalProposalId");

                            b1.ToTable("Proposal");

                            b1.WithOwner()
                                .HasForeignKey("SubmitProposalProposalId");
                        });

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
